joy_node:
  deadzone: 0.01
  autorepeat_rate: 20
  coalesce_interval: 0.01

teleop:
  # Default mode - Stop for safety
  default:
    type: topic
    is_default: true
    message_type: ackermann_msgs/AckermannDriveStamped
    topic_name: donkey_teleop
    message_value:
      -
        target: drive.steering_angle
        value: 0.0
      -
        target: drive.jerk
        value: 0.0
      -
        target: drive.speed
        value: 0.0
      -
        target: drive.acceleration
        value: 0.0
      -
        target: drive.steering_angle_velocity
        value: 0.0
  # Enable Human control by holding Left Bumper
  human_control:
    type: topic
    message_type: ackermann_msgs/AckermannDriveStamped
    topic_name: donkey_teleop
    deadman_buttons: [6]
    axis_mappings:
      -
        axis: 0
        target: drive.steering_angle
        scale: 4096.0                
        offset: 0.0
      -
        axis: 1
        target: drive.jerk
        scale: 4096.0                  
        offset: 0.0
      -
        axis: 2
        target: drive.speed
        scale: 4096.0                  
        offset: 0.0
      -
        axis: 3
        target: drive.acceleration
        scale: 4096.0                  
        offset: 0.0     
      -
        axis: 7
        target: drive.steering_angle_velocity
        scale: 4096.0                  
        offset: 0.0         

  # Enable autonomous control by pressing right bumper
  # This switch causes the joy_teleop to stop sending messages to input/teleop
  # And send messages to /dev/null (an unused ROS topic)
  autonomous_control:
    type: topic
    message_type: std_msgs/Int8
    topic_name: /dev/null
    deadman_buttons: [5]
    message_value:
      -
        target: data
        value: 0
